settings :
  debug : true

application:
  docs_path : 'docs'
  docs_index_file : 'index.yaml'

view  :
 template_path : 'app/templates'
 twig :
    cache : 'cache/twig'
    debug : true

db  :
    host      : 'localhost'
    username  : 'root'
    password  : ''


